### ISSUE TITLE
Some metrics seems to be skipped on exceptions

### ISSUE THREAD

**Issue by tjoyal** [Shopify/statsd-instrument#110]
Based of some dashboard data it lead me to believe we do not properly collect the data correctly on exceptions (at least `measure`). I didn't explore it with more depth but looking at the code that seems to be the case (should at least add a test to cover that).

Eg.: https://github.com/Shopify/statsd-instrument/blob/46df2c67ec9a9384b9b667df13497a884d560278/lib/statsd/instrument.rb#L85

A good scenario where this would occur often by design is when measuring an http request that have an open or read timeout. In these cases, we wouldn't not record failures and it would lead the event consumers to believe "it never happen" while in reality we are simply not issuing event for them.

cc @maximebedard

**Comment by maximebedard** [comment]
I've been able to reproduce fairly easily. I'll see if I can put up a fix ASAP

```rb
irb(main):021:0> StatsD.backend = StatsD::Instrument::Backends::LoggerBackend.new(Logger.new(STDOUT))
irb(main):019:0> StatsD.measure('werwerwer'){puts "asdasd"}
asdasd
I, [2017-10-30T13:05:01.074645 #96755]  INFO -- : [StatsD] measure werwerwer:0.023999949917197227
=> nil
irb(main):020:0> StatsD.measure('werwerwer'){raise "asdasd"}
RuntimeError: asdasd
	from (irb):20:in `block in irb_binding'
	from /Users/maximebedard/.gem/ruby/2.3.3/gems/statsd-instrument-2.1.4/lib/statsd/instrument.rb:287:in `block in measure'
	from /Users/maximebedard/.gem/ruby/2.3.3/gems/statsd-instrument-2.1.4/lib/statsd/instrument.rb:63:in `duration'
	from /Users/maximebedard/.gem/ruby/2.3.3/gems/statsd-instrument-2.1.4/lib/statsd/instrument.rb:287:in `measure'
	from (irb):20
	from /opt/rubies/2.3.3/bin/irb:11:in `<main>'
```
