### ISSUE TITLE
NoMethodError: undefined method shopifycloud.assets.upload_threads:1|c' for nil:NilClass

### ISSUE THREAD

**Issue by mkobetic** [Shopify/statsd-instrument#146]
This showed up when a cloud app didn't set the statsd env vars properly and ended up with invalid StatsD configuration. The stack trace was
```
[FATAL][2018-11-07 13:58:11 +0000]	      Starting asset upload to cdn.shopifycloud.com
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      #<Thread:0x0000000004aa37d8@/app/vendor/bundle/ruby/2.5.0/gems/shopify-cloud-1.4.2/lib/shopify-cloud/asset_uploading/asset_uploader.rb:124 run> terminated with exception (report_on_exception is true):
[FATAL][2018-11-07 13:58:11 +0000]	      /app/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.3.0/lib/statsd/instrument/backends/udp_backend.rb:140:in `block in write_packet': undefined method `shopifycloud.assets.upload_threads:1|c' for nil:NilClass (NoMethodError)
[FATAL][2018-11-07 13:58:11 +0000]	      from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
[FATAL][2018-11-07 13:58:11 +0000]	      from /app/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.3.0/lib/statsd/instrument/backends/udp_backend.rb:139:in `write_packet'
[FATAL][2018-11-07 13:58:11 +0000]	      from /app/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.3.0/lib/statsd/instrument/backends/udp_backend.rb:111:in `collect_metric'
[FATAL][2018-11-07 13:58:11 +0000]	      from /app/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.3.0/lib/statsd/instrument.rb:456:in `collect_metric'
[FATAL][2018-11-07 13:58:11 +0000]	      from /app/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.3.0/lib/statsd/instrument.rb:332:in `increment'
[FATAL][2018-11-07 13:58:11 +0000]	      from /app/vendor/bundle/ruby/2.5.0/gems/shopify-cloud-1.4.2/lib/shopify-cloud/asset_uploading/asset_uploader.rb:125:in `block (2 levels) in consume_in_parallel'
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      [StatsD] Errno::ECONNREFUSED: Connection refused - send(2)
[FATAL][2018-11-07 13:58:11 +0000]	      rake aborted!
[FATAL][2018-11-07 13:58:11 +0000]	      NoMethodError: undefined method `shopifycloud.assets.upload_threads:1|c' for nil:NilClass
[FATAL][2018-11-07 13:58:11 +0000]	      /app/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.3.0/lib/statsd/instrument/backends/udp_backend.rb:140:in `block in write_packet'
[FATAL][2018-11-07 13:58:11 +0000]	      /app/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.3.0/lib/statsd/instrument/backends/udp_backend.rb:139:in `write_packet'
[FATAL][2018-11-07 13:58:11 +0000]	      /app/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.3.0/lib/statsd/instrument/backends/udp_backend.rb:111:in `collect_metric'
[FATAL][2018-11-07 13:58:11 +0000]	      /app/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.3.0/lib/statsd/instrument.rb:456:in `collect_metric'
[FATAL][2018-11-07 13:58:11 +0000]	      /app/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.3.0/lib/statsd/instrument.rb:332:in `increment'
[FATAL][2018-11-07 13:58:11 +0000]	      /app/vendor/bundle/ruby/2.5.0/gems/shopify-cloud-1.4.2/lib/shopify-cloud/asset_uploading/asset_uploader.rb:125:in `block (2 levels) in consume_in_parallel'
[FATAL][2018-11-07 13:58:11 +0000]	      Tasks: TOP => cloudplatform:upload_assets
[FATAL][2018-11-07 13:58:11 +0000]	      (See full trace by running task with --trace)
```

It  seems that somehow the socket on line https://github.com/Shopify/statsd-instrument/blob/master/lib/statsd/instrument/backends/udp_backend.rb#L140 can end up being nil (despite the existing nil guards) and ends up turning the packet write into a message send, with the message being the statsd datagram payload.

/cc @clayton-shopify

**Comment by mkobetic** [comment]
This could be related to #135 /cc @sirupsen @fw42

**Comment by fw42** [comment]
I think `invalidate_socket` might need to be mutexed, otherwise there's a raise where someone is inside of the critical region of the `socket` mutex, already after the `nil` check, and then it gets set to `nil`.

**Comment by mkobetic** [comment]
That would make sense, does that mean the asset uploads are running multi-threaded?
