### ISSUE TITLE
Unable to require statsd/instrument if rspec already required

### ISSUE THREAD

**Issue by inglesp** [Shopify/statsd-instrument#77]
If a project is using rspec 2, you cannot require statsd/instrument if you've already required rspec:

```
$ bundle exec irb
irb(main):001:0> require "rspec"
=> true
irb(main):002:0> require "statsd/instrument"
NameError: uninitialized constant RSpec::Matchers::Composable
	from /Users/peteringlesby/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/statsd-instrument-2.0.11/lib/statsd/instrument/matchers.rb:14:in `<class:Matcher>'
	from /Users/peteringlesby/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/statsd-instrument-2.0.11/lib/statsd/instrument/matchers.rb:13:in `<module:Matchers>'
	from /Users/peteringlesby/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/statsd-instrument-2.0.11/lib/statsd/instrument/matchers.rb:3:in `<top (required)>'
	from /Users/peteringlesby/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/statsd-instrument-2.0.11/lib/statsd/instrument.rb:382:in `require'
	from /Users/peteringlesby/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/statsd-instrument-2.0.11/lib/statsd/instrument.rb:382:in `<top (required)>'
	from (irb):2:in `require'
	from (irb):2
	from /Users/peteringlesby/.rbenv/versions/2.0.0-p353/bin/irb:12:in `<main>'
```

Requiring statsd/instrument by itself works fine:

```
$ bundle exec irb
irb(main):001:0> require "statsd/instrument"
=> true
```

There are no problems with rspec 3.

I've tested with rspec 2.11.1, and rspec 3.4.4, with the most recent version of stats-instrument.

**Comment by wvanbergen** [comment]
The problem most likely is https://github.com/Shopify/statsd-instrument/blob/master/lib/statsd/instrument.rb#L382

We're not using rspec ourselves; it was contributed to this library by someone else. If you can find a fix that will make it work with RSpec 2 as well, I am happy to merge it.
