### ISSUE TITLE
Calling `statsd_measure` after prepending a module causes infinite loop

### ISSUE THREAD

**Issue by sgrif** [Shopify/statsd-instrument#91]
To reproduce:

```ruby
require "bundler/inline"

gemfile(true) do
  gem "statsd-instrument", github: "shopify/statsd-instrument"
end

class Foo
  def foo
    puts "foo"
  end
end

module MyPatch
  def foo
    puts "before foo"
    super
  end
end

Foo.prepend(MyPatch)

Foo.extend(StatsD::Instrument)
Foo.statsd_measure :foo, "Foo!"

Foo.new.foo
```

Output:

```
before foo
before foo
before foo
before foo
before foo
before foo
before foo
before foo
before foo
/Users/sean/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/statsd-instrument-154487eb6a1d/lib/statsd/instrument.rb:75:in `block (3 levels) in statsd_measure': stack level too deep (SystemStackError)
	from /Users/sean/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/statsd-instrument-154487eb6a1d/lib/statsd/instrument.rb:284:in `block in measure'
	from /Users/sean/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/statsd-instrument-154487eb6a1d/lib/statsd/instrument.rb:53:in `duration'
	from /Users/sean/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/statsd-instrument-154487eb6a1d/lib/statsd/instrument.rb:284:in `measure'
	from /Users/sean/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/statsd-instrument-154487eb6a1d/lib/statsd/instrument.rb:75:in `block (2 levels) in statsd_measure'
	from foo.rb:16:in `foo'
	from /Users/sean/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/statsd-instrument-154487eb6a1d/lib/statsd/instrument.rb:75:in `block (3 levels) in statsd_measure'
	from /Users/sean/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/statsd-instrument-154487eb6a1d/lib/statsd/instrument.rb:284:in `block in measure'
	from /Users/sean/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/statsd-instrument-154487eb6a1d/lib/statsd/instrument.rb:53:in `duration'
	 ... 10758 levels...
	from /Users/sean/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/statsd-instrument-154487eb6a1d/lib/statsd/instrument.rb:284:in `measure'
	from /Users/sean/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/statsd-instrument-154487eb6a1d/lib/statsd/instrument.rb:75:in `block (2 levels) in statsd_measure'
	from foo.rb:16:in `foo'
	from foo.rb:25:in `<main>'
```

This would likely be solved by changing `statsd_measure` to use `Module.prepend`, which this gem can now do as it doesn't support 1.9.3

**Comment by wvanbergen** [comment]
I think that should work; we just need to generate the module on demand because method names depend on the method that is being instrumented. Shouldn't be too hard.

**Comment by sgrif** [comment]
Yeah I'm about to submit a PR
